version: '3'

tasks:
  build:
    cmds:
      - cmake --preset config
      - source /opt/ros/humble/setup.sh && cmake --build --preset build
      # - sudo cmake --build --preset build --target install
    


